name: master on CLN v25.05.x

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'tools/**'
            - 'CHANGELOG.md'
            - 'README.md'
            - 'LICENSE'
            - '.gitignore'
            - 'coffee.yml'
            - 'tests/setup.sh'
    pull_request:
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v25.05"
            pyln-version: "25.5"
            tagged-release: false
